### ISSUE TITLE
M1 Mac - bus error

### ISSUE THREAD

**Issue by LordKaaahl** [invoke-ai/InvokeAI#1115]
Mac Studio M1 Ultra

When I run: python scripts/invoke.py

I get the following error:

`* Initializing, be patient...
zsh: bus error  python scripts/invoke.py`

**Comment by mauwii** [comment]
could you please do a "`which python`" (or if you are using pyenv `pyenv which python`) and post its return?

**Comment by LordKaaahl** [comment]
`/Users/xxx/miniconda3/envs/invokeai/bin/python`

and here's which -a python3

```
/Users/xxx/miniconda3/envs/invokeai/bin/python3
/Library/Frameworks/Python.framework/Versions/3.10/bin/python3
/opt/homebrew/bin/python3
/usr/local/bin/python3
/usr/bin/python3
```

**Comment by LordKaaahl** [comment]
Did a reinstall and now I'm getting these errors after successfully running **python scripts/preload_models.py**


**python scripts/invoke.py**
```
Traceback (most recent call last):
  File "/Users/xxx/InvokeAI/scripts/invoke.py", line 19, in <module>
    from backend.invoke_ai_web_server import InvokeAIWebServer
  File "/Users/xxx/InvokeAI/./backend/invoke_ai_web_server.py", line 9, in <module>
    from flask import Flask, redirect, send_from_directory
  File "/Users/xxx/miniconda3/envs/invokeai/lib/python3.9/site-packages/flask/__init__.py", line 4, in <module>
    from . import json as json
  File "/Users/xxx/miniconda3/envs/invokeai/lib/python3.9/site-packages/flask/json/__init__.py", line 8, in <module>
    from ..globals import current_app
  File "/Users/xxx/miniconda3/envs/invokeai/lib/python3.9/site-packages/flask/globals.py", line 56, in <module>
    app_ctx: "AppContext" = LocalProxy(  # type: ignore[assignment]
TypeError: __init__() got an unexpected keyword argument 'unbound_message'
```

**Comment by mauwii** [comment]
Could you try to first uninstall current invokeai conda env

```bash
# disable invokeai
conda deactivate

# uninstall invokeai
conda env remove -n invokeai
```

and then reinstall it by using this yaml which has no pinned versions:

```yaml
name: invokeai
channels:
  - pytorch
  - conda-forge
dependencies:
  - python>=3.10, <3.11

  # pytorch left unpinned
  - pytorch
  - torchvision
  # I suggest to keep the other deps sorted for convenience.
  # To determine what the latest versions should be, run:
  #
  # ```shell
  # sed -E 's/invokeai/invokeai-updated/;20,99s/- ([^=]+)==.+/- \1/' environment-mac.yml > environment-mac-updated.yml
  # CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac-updated.yml && conda list -n invokeai-updated | awk ' {print "  - " $1 "==" $2;} '
  # ```
  - albumentations
  - coloredlogs
  - einops
  - grpcio
  - humanfriendly
  - imageio
  - imageio-ffmpeg
  - imgaug
  - kornia
  - mpmath
  - nomkl
  - numpy
  - omegaconf
  - openh264
  - onnx
  - onnxruntime
  - pudb
  - pytorch-lightning
  - scipy
  - streamlit
  - sympy
  - tensorboard
  - torchmetrics
  - pip:
      - flask
      - flask_socketio
      - flask_cors
      - dependency_injector
      - eventlet
      - protobuf
      - realesrgan
      - send2trash
      - test-tube
      - transformers
      - torch-fidelity
      - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
      - -e git+https://github.com/openai/CLIP.git@main#egg=clip
      - -e git+https://github.com/Birch-san/k-diffusion.git@mps#egg=k_diffusion
      - -e git+https://github.com/TencentARC/GFPGAN.git#egg=gfpgan
      - -e .
variables:
  PYTORCH_ENABLE_MPS_FALLBACK: 1
```
