### ISSUE TITLE
Step conda env create doesn't work on macos x64

### ISSUE THREAD

**Issue by VladimirKempik** [invoke-ai/InvokeAI#1121]
**Describe your environment**
- GPU: [amd]
- VRAM: [4g]
- CPU arch: [x86]
- OS: [macOS]
- Python: [Anaconda/miniconda/miniforge/pyenv/other (explain)]
- Branch: [if `git status` says anything other than "On branch main" paste it here]
- Commit: [run `git show` and paste the line that starts with "Merge" here]

Running 
PIP_EXISTS_ACTION=w CONDA_SUBDIR=osx-64 conda env create -f environment-mac.yml
in the end getting:

Package python-dateutil conflicts for:
streamlit==1.12.2 -> python-dateutil
streamlit==1.12.2 -> pandas[version='>=0.21.0'] -> python-dateutil[version='>=2.5.*|>=2.6.1|>=2.7.3|>=2.8.1']The following specifications were found to be incompatible with your system:

  - feature:/osx-64::__osx==10.16=0
  - feature:|@/osx-64::__osx==10.16=0
  - grpcio==1.46.4 -> __osx[version='>=10.9']
  - imgaug==0.4.0 -> matplotlib-base -> __osx[version='>=10.12']
  - kornia==0.6.7 -> pytorch[version='>=1.10'] -> __osx[version='>=10.9']
  - pytorch-lightning==1.7.5 -> pytorch[version='>=1.9'] -> __osx[version='>=10.9']
  - tensorboard==2.10.0 -> grpcio[version='>=1.24.3'] -> __osx[version='>=10.10|>=10.9']
  - torchmetrics==0.9.3 -> pytorch[version='>=1.3.1'] -> __osx[version='>=10.9']

Your installed version is: 10.16

**Comment by mauwii** [comment]
I finaly got the installation working by removing all the pinned Versions.

So in the end it worked with a yml like this:

```yaml
name: invokeai
channels:
  - pytorch
  - conda-forge
dependencies:
  - python>=3.10, <3.11
  - pip>=22

  # pytorch left unpinned
  - pytorch
  - torchvision
  # I suggest to keep the other deps sorted for convenience.
  # To determine what the latest versions should be, run:
  #
  # ```shell
  # sed -E 's/invokeai/invokeai-updated/;20,99s/- ([^=]+)==.+/- \1/' environment-mac.yml > environment-mac-updated.yml
  # CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac-updated.yml && conda list -n invokeai-updated | awk ' {print "  - " $1 "==" $2;} '
  # ```
  - albumentations
  - coloredlogs
  - einops
  - grpcio
  - humanfriendly
  - imageio
  - imageio-ffmpeg
  - imgaug
  - kornia
  - mpmath
  - nomkl
  - numpy
  - omegaconf
  - openh264
  - onnx
  - onnxruntime
  - pudb
  - pytorch-lightning
  - scipy
  - streamlit
  - sympy
  - tensorboard
  - torchmetrics
  - pip:
      - flask
      - flask_socketio
      - flask_cors
      - dependency_injector
      - eventlet
      - protobuf
      - realesrgan
      - send2trash
      - test-tube
      - transformers
      - torch-fidelity
      - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
      - -e git+https://github.com/openai/CLIP.git@main#egg=clip
      - -e git+https://github.com/Birch-san/k-diffusion.git@mps#egg=k_diffusion
      - -e git+https://github.com/TencentARC/GFPGAN.git#egg=gfpgan
      - -e .
variables:
  PYTORCH_ENABLE_MPS_FALLBACK: 1
```

**Comment by alessandro893** [comment]
Try this: https://drive.google.com/file/d/11iz4cZDOeUc9ulJbPtothgRcNf3Dg32-/view?usp=sharing

It's my InvokeAI environment, just extract it and copy to your Conda "env" directory, rename to InvokeAI.
Tested on Macbook Pro, Mac Pro 5.1 AMD Vega 64 (both have Monterey 12.4)

InvokeAI folder located under InvokeAI environment dir, 
don't forget to place "model.ckpt" in /miniforge3/envs/InvokeAI/InvokeAI/models/ldm/stable-diffusion-v1/model.ckpt

## Change paths in commands below to fit your installation ##
Usage:
cd /miniforge3/envs/InvokeAI/InvokeAI
source /miniforge3/bin/activate
conda activate InvokeAI
python /miniforge3/envs/InvokeAI/InvokeAI/scripts/invoke.py --web

**Comment by lstein** [comment]
@magnusviri, @Any-Winter-4079 Could one of you take another pass at the Mac environment file and/or documentation?

**Comment by mauwii** [comment]
So the File I posted earlier is at least working on a x64 macOS runner in GH-Actions, so I could imagine it would also work here 🤷🏻‍♂️

**Comment by mauwii** [comment]
Out of the stomache I would say you did not activate the conda environment. This has something to do with the python-binary itself, since there is no code-signing for python scripts
But since you call the script with python and this links to some python3.9 executable, it would be at least necesarry to get the returns of:

- `which python`
- `which python3.9`

those commands needs to be executed at exactly the point where you tried to execute

`python /miniconda3/envs/InvokeAI/InvokeAI/scripts/invoke.py`

But from looking at the Path where the script is located (`/miniconda3/envs/InvokeAI/InvokeAI/scripts/invoke.py`) I can already tell you for sure that you did not follow the steps correctly (since creating something on root level would require root permissions ...), or that you did not provide correct information here ;P

**Comment by mauwii** [comment]
For the others who started this issue: this is the last environment yaml I used to successfully create a env from x64 and ARM with the same file:

```yaml
name: invokeai
channels:
  - pytorch
  - conda-forge
dependencies:
  - python>=3.9, <3.10
  - pip>=22.2

  # pytorch left unpinned
  - pytorch
  - torchvision
  # I suggest to keep the other deps sorted for convenience.
  # To determine what the latest versions should be, run:
  #
  # ```shell
  # sed -E 's/invokeai/invokeai-updated/;20,99s/- ([^=]+)==.+/- \1/' environment-mac.yml > environment-mac-updated.yml
  # CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac-updated.yml && conda list -n invokeai-updated | awk ' {print "  - " $1 "==" $2;} '
  # ```
  - albumentations
  - coloredlogs
  - einops
  - grpcio
  - humanfriendly
  - imageio
  - imageio-ffmpeg
  - imgaug
  - kornia
  - mpmath
  - nomkl
  - numpy
  - omegaconf
  - openh264
  - onnx
  - onnxruntime
  - pudb
  - pytorch-lightning
  - scipy
  - streamlit
  - sympy
  - tensorboard
  - torchmetrics
  - pip:
      - flask==2.1.3
      - flask_socketio==5.3.0
      - flask_cors==3.0.10
      - dependency_injector==4.40.0
      - eventlet==0.33.1
      - protobuf==3.19.5
      - realesrgan==0.2.5.0
      - send2trash==1.8.0
      - test-tube==0.7.5
      - transformers==4.21.2
      - torch-fidelity==0.3.0
      - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
      - -e git+https://github.com/openai/CLIP.git@main#egg=clip
      - -e git+https://github.com/Birch-san/k-diffusion.git@mps#egg=k_diffusion
      - -e git+https://github.com/TencentARC/GFPGAN.git#egg=gfpgan
      - -e .
variables:
  PYTORCH_ENABLE_MPS_FALLBACK: 1
```
