### ISSUE TITLE
VAE (vae-ft-mse-840000-ema-pruned.ckpt) Documentation

### ISSUE THREAD

**Issue by Any-Winter-4079** [invoke-ai/InvokeAI#1279]
Finally got to try `vae-ft-mse-840000-ema-pruned.ckpt` and my first impression is wow: seems to do better with eyes! Have you noticed some other benefits (e.g. for landscapes, etc.)? I think it would be good to document the strengths and weaknesses of this new vae and also add it to the docs.
<img width="900" alt="image" src="https://user-images.githubusercontent.com/50542132/198444197-945c2293-00e5-4d43-a9c7-d5f4c045324e.png">

**Comment by mauwii** [comment]
what where the prompts you used?

**Comment by Any-Winter-4079** [comment]
```
miranda kerr closeup -s 50 -S 2328329510 -W 512 -H 512 -C 7.5 -A k_lms
miranda kerr closeup -s 50 -S 1641815931 -W 512 -H 512 -C 7.5 -A k_lms
miranda kerr closeup -s 50 -S 1502365647 -W 512 -H 512 -C 7.5 -A k_lms
```

**Comment by mauwii** [comment]
Would like to compare what they look on my end, since I did not have those problematic Faces.

Will test after MacOS Update is done ^^

**Comment by michaelezra** [comment]
Are there any instructions how to use it with InvokeAI?

**Comment by mauwii** [comment]
not sure if it is related to the updated macOS Ventura, but when running in main branch I know have 5.*s/it (instead of 2.*s/it) 🤔

**Comment by Any-Winter-4079** [comment]
> Are there any instructions how to use it with InvokeAI?

@michaelezra In `models.yaml`:

```
stable-diffusion-1.4:
  config: configs/stable-diffusion/v1-inference.yaml
  weights: models/ldm/stable-diffusion-v1/model.ckpt
  description: Stable Diffusion inference model version 1.4
  vae: models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
  width: 512
  height: 512

```
add vae to the model(s). Download: https://huggingface.co/stabilityai/sd-vae-ft-mse-original/tree/main

**Comment by Any-Winter-4079** [comment]
@mauwii Interesting. I didn't use `FFHQ_eye_mouth_landmarks_512.pth` or `StyleGAN2_512_Cmul1_FFHQ_B12G4_scratch_800k.pth`for any of the results posted above, but it seems to achieve a similar purpose to `vae-ft-mse-840000-ema-pruned.ckpt`.

**Comment by Any-Winter-4079** [comment]
<img width="754" alt="image" src="https://user-images.githubusercontent.com/50542132/198833051-85c9b6cf-a0f2-4bbb-90cb-1b591a68e6fb.png">

**Comment by mauwii** [comment]
> I assume after doing this, your command changed and you passed some post-processing options? e.g. `miranda kerr closeup -s 50 -S 2328329510 -W 512 -H 512 -C 7.5 -A k_lms -G 0.6 -ft gfpgan`

Oh, yes, sorry, should have mentioned this. What happened: When I created the first picture i was totally iritated since my GFPGAN was broken as well so even postprocessing wasnt working anymore (which I guess came from about 100 reinstallations while "playing" with the environment-mac.yml 🙈).

Long story short - the second picture was postprocessed with GFPGAN 🤦🏻‍♂️ Hope I did not lead you on some non-existing route!

**Comment by Any-Winter-4079** [comment]
All good! I figured you were passing GFPGAN to get so good of a result :)
Here's another comparison:
<img width="753" alt="image" src="https://user-images.githubusercontent.com/50542132/198833262-6c0aea28-eabb-48f5-b761-90ff545651e9.png">

**Comment by mauwii** [comment]
I edited the post and added the prompt `miranda kerr closeup" -s 50 -S 2328329510 -W 512 -H 512 -C 7.5 -A k_lms -G 0.7` which should be the one I used there

**Comment by Any-Winter-4079** [comment]
Do you think it may be useful to include these results / comparisons in https://github.com/invoke-ai/InvokeAI/blob/development/docs/features/POSTPROCESS.md?
There's no photos right now that document what one may expect.

**Comment by mauwii** [comment]
I guess your excelent comparison-screenshots would ofc fit very well onto the postprocessing docs, since Pics (especially in this case) sometimes say more than 100 lines of docs could do 🙈

**Comment by michaelezra** [comment]
@Any-Winter-4079 Thanks!

in models.yaml I tried v1.5:

```
stable-diffusion-1.5:
    config:  configs/stable-diffusion/v1-inference.yaml
    weights: models/ldm/stable-diffusion-v1/v1-5-pruned-emaonly.ckpt
    description: Stable Diffusion inference model version 1.5
    vae: models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
    width: 512
    height: 512
```


I created a symlink to vae-ft-mse-840000-ema-pruned.ckpt
and starting invokeai:

`(invokeai) michaelezra@Michaels-MBP stable-diffusion % PATH_TO_CKPT="/Users/michaelezra/ai/CKPT"   
(invokeai) michaelezra@Michaels-MBP stable-diffusion % ln -s "$PATH_TO_CKPT/vae-ft-mse-840000-ema-pruned.ckpt" models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt

(invokeai) michaelezra@Michaels-MBP stable-diffusion % python scripts/invoke.py --web --model stable-diffusion-1.5                                                        
* Initializing, be patient...
NOTE: Redirects are currently not supported in Windows or MacOs.
>> GFPGAN Initialized
>> CodeFormer Initialized
>> ESRGAN Initialized
>> Using device_type mps
>> Loading stable-diffusion-1.5 from models/ldm/stable-diffusion-v1/v1-5-pruned-emaonly.ckpt
   | LatentDiffusion: Running in eps-prediction mode
   | DiffusionWrapper has 859.52 M params.
   | Making attention of type 'vanilla' with 512 in_channels
   | Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
   | Making attention of type 'vanilla' with 512 in_channels
   | Using more accurate float32 precision
>> Model loaded in 5.93s
>> Setting Sampler to k_lms`

Does this look right - no message about vae. 
Should I use any additional command line parameter for invoke.py?
