### ISSUE TITLE
[bug]: "TypeError: 'type' object is not subscriptable" when calling invoke.py

### ISSUE THREAD

**Issue by viktorzen** [invoke-ai/InvokeAI#1380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

Cannot start invoke.py any more after updating to version 2.1

```
(ldm) D:\Stable Diffusion\InvokeAI>python scripts/invoke.py
Traceback (most recent call last):
  File "scripts/invoke.py", line 14, in <module>
    from ldm.invoke.prompt_parser import PromptParser
  File "d:\stable diffusion\invokeai\ldm\invoke\prompt_parser.py", line 211, in <module>
    class Blend():
  File "d:\stable diffusion\invokeai\ldm\invoke\prompt_parser.py", line 217, in Blend
    def __init__(self, prompts: list, weights: list[float], normalize_weights: bool=True):
TypeError: 'type' object is not subscriptable
```

**Comment by THEGOLDENPRO** [comment]
What python version are you using? Using python 3.9 and above fixed this issue for me as in python 3.8 and below you can't do "list" typings like that. ``from typing import List`` would fix this but invoke ai still wouldn't work as "clipseg" doesn't support 3.8.

So moving over to 3.9 may fix your issue.

![image](https://user-images.githubusercontent.com/66202304/200126759-087936b2-214f-4b27-a6e1-39aae274a462.png)

**Comment by viktorzen** [comment]
running Python 3.9.12 (Anaconda)

**Comment by viktorzen** [comment]
Python 3.9.12

**Comment by viktorzen** [comment]
still having the same problem

**Comment by viktorzen** [comment]
I updated to Python 3.10.6 and reinstalled involie-ai

now I get another error message when launching invoke.py

```
** "stable-diffusion-1.5" is not a known model name. Please check your models.yaml file
...
TypeError: 'NoneType' object is not subscriptable
```

my model.yam file looks like this

```
# This file describes the alternative machine learning models
# available to InvokeAI script.
#
# To add a new model, follow the examples below. Each
# model requires a model config file, a weights file,
# and the width and height of the images it
# was trained on.
stable-diffusion-1.4:
  description: Stable Diffusion inference model version 1.4
  config: configs/stable-diffusion/v1-inference.yaml
  weights: models/ldm/stable-diffusion-v1/sd-v1-4.ckpt
  vae: models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
  width: 512
  height: 512
```

**Comment by THEGOLDENPRO** [comment]
Umm, I'm not sure about this one. Your last issue looks like it's fixed, this seems like a completely different issue, more specifically when trying to load the models.

I'm also getting this error. Idk why it's trying to load `stable-diffusion-1.5` when that hasn't been specified in the `.yaml` file.

Let's create another issue for this shall we.

**Comment by viktorzen** [comment]
thx, found the bug:

default:true was missing in the ./configs/models.yaml file

```
stable-diffusion-1.4:
  description: Stable Diffusion inference model version 1.4
  config: configs/stable-diffusion/v1-inference.yaml
  weights: models/ldm/stable-diffusion-v1/sd-v1-4.ckpt
  vae: models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
  width: 512
  height: 512
  default: true
```
