### ISSUE TITLE
[diffusers]: Model Manager

### ISSUE THREAD

**Issue by keturn** [invoke-ai/InvokeAI#2160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Model Manager needs some changes to support diffusers models:

- **Description:** this stays the same!
- **Config:** remove; a model's config file is always in a standard location in its directory
- **Model Location:** needs to offer two options:
  - `path` for a local filesystem path, OR
  - `repo_id` for a model hosted on 🤗, e.g. `CompVis/stable-diffusion-v1-4`
- **VAE Location:** needs the same `path` or `repo_id` option as Model Location.
  - There might be a use case for `subfolder` as well, as some repositories are _only_ a VAE like [stabilityai/sd-vae-ft-mse](https://huggingface.co/stabilityai/sd-vae-ft-mse/tree/main), but you might also want to load just the VAE from a repository that has one in a subdirectory, like [runwayml/stable-diffusion-v1-5 subfolder=/vae](https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main/vae). Or maybe we define some syntax (like a colon separator) to make that part of a single string?
- **Width** and **Height:** remove; we get these from the model's own settings.

**Comment by blessedcoolant** [comment]
This will need rewriting of how the models.yaml is handled on the backend. Once @lstein does it on the backend, I'll make the necessary changes to the frontend.

**Comment by lstein** [comment]
> VAE Location: needs the same path or repo_id option as Model Location.
There might be a use case for subfolder as well, as some repositories are only a VAE like [stabilityai/sd-vae-ft-mse](https://huggingface.co/stabilityai/sd-vae-ft-mse/tree/main), but you might also want to load just the VAE from a repository that has one in a subdirectory, like [runwayml/stable-diffusion-v1-5 subfolder=vae](https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main/vae). Or maybe we define some syntax (like a colon separator) to make that part of a single string?

I'm writing the support for vae subfolders. Here is what I understand the task to be. Please confirm.

**Case 1: No VAE entry** (already supported)
```
stable-diffusion-2.1:
  description: Stable Diffusion version 2.1 diffusers model (5.21 GB)
  repo_id: stabilityai/stable-diffusion-2-1
  format: diffusers
```
  In this case, we just load the diffuser model and whatever vae model is in the `vae` subdirectory will be used by default.

**Case 2: VAE-specific model entry** (already supported)
```
stable-diffusion-2.1:
  description: Stable Diffusion version 2.1 diffusers model (5.21 GB)
  repo_id: stabilityai/stable-diffusion-2-1
  format: diffusers
  vae:
      repo_id: stabilityai/sd-vae-ft-mse
```
In this case, we download the vae, load it, and replace the main model's VAE with this one.

**Case 3: VAE in a subfolder of another model** (not supported)
```
stable-diffusion-2.1:
  description: Stable Diffusion version 2.1 diffusers model (5.21 GB)
  repo_id: stabilityai/stable-diffusion-2-1
  format: diffusers
  vae:
      repo_id: runwayml/stable-diffusion-1.5
      subfolder: vae
```
In this case, we're going to load the model located in `runwayml/stable-diffusion-1.5` subdirectory `vae` and replace the main model's VAE with this one.

Is this the correct behavior?
