### ISSUE TITLE
[enhancement]: Support local diffusers format models

### ISSUE THREAD

**Issue by subpanic** [invoke-ai/InvokeAI#2361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

It appears currently Invoke is only setup to work with huggingface hosted diffusers models with a local caching mechanism for them. Would be extremely useful if we could also add local diffusers models from arbitrary paths. In particular thinking about people trying to do training and there not being a great inference tool out there for testing locally trained diffusers models.

### Alternatives

Alternative would be requiring people to always upload diffusers models to huggingface, including WIP models

### Aditional Content

Ideally this would just involve adding the fields/option to the models config UI for diffusers models.

**Comment by SnakePin** [comment]
Local diffusers models are already supported, you can load them like so in the models.yaml file: 
```yaml
diffusers_model:
  path: /path/to/diffusers/model/folder
  description: A lovely 🤗 model
  format: diffusers
  ```
