### ISSUE TITLE
[bug]: 2.3.0 - VAE showing up in Models List 

### ISSUE THREAD

**Issue by ShaguarWKL** [invoke-ai/InvokeAI#2571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

blessed and istein knows about this. Just posting this up for issue tracking.

### Screenshots

![msedge_2023-02-08_01-12-46](https://user-images.githubusercontent.com/104881834/217338961-bd722592-db29-41f7-b42a-59af33e2a66a.png)
![msedge_2023-02-08_01-12-39](https://user-images.githubusercontent.com/104881834/217338992-ae06dc7b-3753-4216-be94-547d051ac73c.png)

**Comment by lstein** [comment]
Thanks for the report.

**Comment by psychedelicious** [comment]
I've downloaded the trinart vae and cannot get it to show up in the model manager at all. Can you please post your `configs/models.yaml` file?

**Comment by ShaguarWKL** [comment]
> I've downloaded the trinart vae and cannot get it to show up in the model manager at all - cannot reproduce this. Can you please post your `configs/models.yaml` file?

I've deleted that install. Let me do a new clean install and download all of that and repost it. Will revert back.

**Comment by ShaguarWKL** [comment]
RC6

![WindowsTerminal_2023-02-09_16-31-28](https://user-images.githubusercontent.com/104881834/217773260-45fbbb7d-ce65-485e-b165-46666f722fe4.png)

![WindowsTerminal_2023-02-09_17-21-26](https://user-images.githubusercontent.com/104881834/217785375-31529049-9ef7-4ad7-8f26-969fd02349e3.png)

![msedge_2023-02-09_17-23-02](https://user-images.githubusercontent.com/104881834/217785891-776a7ba3-3dfb-44be-9b82-fc9884d7118e.png)

![msedge_2023-02-09_17-23-07](https://user-images.githubusercontent.com/104881834/217785942-f1bec1f2-439d-466f-9a5b-f91608a6c640.png)

YAML after install
```
# This file describes the alternative machine learning models
# available to InvokeAI script.
#
# To add a new model, follow the examples below. Each
# model requires a model config file, a weights file,
# and the width and height of the images it
# was trained on.
stable-diffusion-1.5:
  description: Stable Diffusion version 1.5 weight file (4.27 GB)
  repo_id: runwayml/stable-diffusion-v1-5
  format: diffusers
  vae:
    repo_id: stabilityai/sd-vae-ft-mse
  default: true
inpainting-1.5:
  description: RunwayML SD 1.5 model optimized for inpainting (4.27 GB)
  repo_id: runwayml/stable-diffusion-inpainting
  format: diffusers
  vae:
    repo_id: stabilityai/sd-vae-ft-mse
dreamlike-diffusion-1.0:
  description: An SD 1.5 model fine tuned on high quality art by dreamlike.art
  repo_id: dreamlike-art/dreamlike-diffusion-1.0
  format: diffusers
  vae:
    repo_id: stabilityai/sd-vae-ft-mse
dreamlike-photoreal-2.0:
  description: A photorealistic model trained on 768 pixel images based on SD 1.5
    (2.13 GB)
  repo_id: dreamlike-art/dreamlike-photoreal-2.0
  format: diffusers
stable-diffusion-2.1-768:
  description: Stable Diffusion version 2.1 diffusers model, trained on 768 pixel
    images (5.21 GB)
  repo_id: stabilityai/stable-diffusion-2-1
  format: diffusers
stable-diffusion-2.1-base:
  description: Stable Diffusion version 2.1 diffusers base model, trained on 512 pixel
    images (5.21 GB)
  repo_id: stabilityai/stable-diffusion-2-1-base
  format: diffusers
openjourney-4.0:
  description: An SD 1.5 model fine tuned on Midjourney images by PromptHero - include
    "mdjrny-v4 style" in your prompts (2.13 GB)
  repo_id: prompthero/openjourney
  format: diffusers
  vae:
    repo_id: stabilityai/sd-vae-ft-mse
nitro-diffusion-1.0:
  description: A SD 1.5 model trained on three artstyles - prompt with "archer style",
    "arcane style" and/or "modern disney style" (2.13 GB)
  repo_id: nitrosocke/Nitro-Diffusion
  format: diffusers
  vae:
    repo_id: stabilityai/sd-vae-ft-mse
trinart-2.0:
  description: An SD model finetuned with ~40,000 assorted high resolution manga/anime-style
    pictures (2.13 GB)
  repo_id: naclbit/trinart_stable_diffusion_v2
  format: diffusers
  vae:
    repo_id: stabilityai/sd-vae-ft-mse
trinart-characters-2_0:
  description: An SD model finetuned with 19.2M anime/manga style images (ckpt version)
    (4.27 GB)
  repo_id: naclbit/trinart_derrida_characters_v2_stable_diffusion
  format: ckpt
  width: 512
  height: 512
  weights: models\ldm\stable-diffusion-v1\derrida_final.ckpt
  config: C:\Users\warre\Downloads\RC6\configs\stable-diffusion\v1-inference.yaml
  vae: models\ldm\stable-diffusion-v1\autoencoder_fix_kl-f8-trinart_characters.ckpt
ft-mse-improved-autoencoder-840000:
  description: StabilityAI improved autoencoder fine-tuned for human faces. Improves
    legacy .ckpt models (335 MB)
  repo_id: stabilityai/sd-vae-ft-mse-original
  format: ckpt
  width: 512
  height: 512
  weights: models\ldm\stable-diffusion-v1\vae-ft-mse-840000-ema-pruned.ckpt
  config: C:\Users\warre\Downloads\RC6\configs\stable-diffusion\VAE\default
trinart_vae:
  description: Custom autoencoder for trinart_characters for legacy .ckpt models only
    (335 MB)
  repo_id: naclbit/trinart_characters_19.2m_stable_diffusion_v1
  format: ckpt
  width: 512
  height: 512
  weights: models\ldm\stable-diffusion-v1\autoencoder_fix_kl-f8-trinart_characters.ckpt
  config: C:\Users\warre\Downloads\RC6\configs\stable-diffusion\VAE\trinart

```
