### ISSUE TITLE
[bug]: keyfile and certfile config keys are ignored - running over SSL is not possible

### ISSUE THREAD

**Issue by dotgrid** [invoke-ai/InvokeAI#3970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24GB

### What version did you experience this issue on?

3.0.0

### What happened?

I have `invokeai.yaml` configured with the options below for `Web Server`, but the local server does not use **https** when I run `invoke.bat`, it starts up on (insecure) `http://localhost:9090` as instead.

```yaml
InvokeAI:
  Web Server:
    host: 0.0.0.0
    port: 9090
    web: true
    useSSL: true
    certfile: D:\dev\ssl\cert.pem
    keyfile: D:\dev\ssl\key.key
    allow_origins: [ '*' ]
    allow_credentials: true
    allow_methods:
    - '*'
    allow_headers:
    - '*'
 
 ...
```
