### ISSUE TITLE
[bug]: Not save imported embeddings and VAE after restart

### ISSUE THREAD

**Issue by vrubzov1957** [invoke-ai/InvokeAI#4557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

11

### What version did you experience this issue on?

3.1.1

### What happened?

Every time when I restart Invoke (command line) - I lost previously imported embedding (from Automatic directory). 
And I need to import embeddings every time.
Same promlem with imported VAE models.

**Comment by lstein** [comment]
@vrubzov1957 Could you please append the `Paths:` section of your `invokeai.yaml` file so that I can take a look?

**Comment by vrubzov1957** [comment]
Sure.


 ```
 Paths:
    autoimport_dir: autoimport
    lora_dir: null
    embedding_dir: null
    controlnet_dir: null
    conf_path: configs\models.yaml
    models_dir: models
    legacy_conf_dir: configs\stable-diffusion
    db_dir: databases
    outdir: D:\InvokeAI_3\outputs
    use_memory_db: false
```
