### ISSUE TITLE
[bug]: unloads model checkpoint after each item then reloads it

### ISSUE THREAD

**Issue by soundreactor** [invoke-ai/InvokeAI#6435]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU model

3079

### GPU VRAM

8GB

### Version number

v4.2.2post1

### Browser

chrome

### What happened

im successfully using a SDXL model checkpoint. it generates the image. but then immediately unloads the model from gpu.? why? how can i stop this? even if the next 5 images in the queue require the same model it unloads it after one generation and then i have to wait 2 min for it to load again.

### What you expected to happen

i would expect it to keep the model loaded for a while or until i switch models. especially if the queue has open items for this model

**Comment by psychedelicious** [comment]
Please share your `invokeai.yaml` config

**Comment by soundreactor** [comment]
im using docker

```
# Copyright (c) 2023 Eugene Brodsky https://github.com/ebr

version: '3.8'

x-invokeai: &invokeai
    image: "local/invokeai:latest"
    build:
      context: ..
      dockerfile: docker/Dockerfile

    # Create a .env file in the same directory as this docker-compose.yml file
    # and populate it with environment variables. See .env.sample
    env_file:
      - .env

    # variables without a default will automatically inherit from the host environment
    environment:
      # if set, CONTAINER_INVOKEAI_ROOT will override the Invoke runtime directory location *inside* the container
      - INVOKEAI_ROOT=${CONTAINER_INVOKEAI_ROOT:-/invokeai}
      - HF_HOME
    ports:
      - "${INVOKEAI_PORT:-9090}:${INVOKEAI_PORT:-9090}"
    volumes:
      - type: bind
        source: ${HOST_INVOKEAI_ROOT:-${INVOKEAI_ROOT:-~/invokeai}}
        target: ${CONTAINER_INVOKEAI_ROOT:-/invokeai}
        bind:
          create_host_path: true
      - ${HF_HOME:-~/.cache/huggingface}:${HF_HOME:-/invokeai/.cache/huggingface}
    tty: true
    stdin_open: true


services:
  invokeai-nvidia:
    <<: *invokeai
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  invokeai-cpu:
    <<: *invokeai
    profiles:
      - cpu

  invokeai-rocm:
    <<: *invokeai
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    profiles:
      - rocm

```
