### ISSUE TITLE
[bug]: Update to 4.2.4 causes CUDA out of memory error in WSL/docker

### ISSUE THREAD

**Issue by jozzo402** [invoke-ai/InvokeAI#6542]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 2060 Super

### GPU VRAM

8GB

### Version number

4.2.4

### Browser

Waterfox G6.0.16

### What happened

When generating with many LORAs added, Invoke 4.2.4 reports that my system is out of memory:
![image](https://github.com/invoke-ai/InvokeAI/assets/11382131/2a894d7e-46e1-4ad7-8548-5e01c43cc14c)

It seems to be filling VRAM, but doesn't fall back to system RAM once VRAM is full, then crashes.
I've changed the fallback setting in Nvidia console to system, it makes no difference.
If I use Invoke 4.2.1, it works fine. Unsure about versions in between.

### What you expected to happen

Overflowing VRAM should fallback to system RAM, and overflowing system RAM should fallback to Swap. It should not throw an error once VRAM is full.

### How to reproduce the problem

Using my setup install Invoke 4.2.1 and generate an image with heavy memory requirements (SDXL, many loras, controlnets, etc). It will work fine.
Then, update to Invoke 4.2.4 and generate another image with the same parameters. It will no longer work and you'll see this error. (use random seed, otherwise it might just copy the last image)

### Additional context

My setup is Windows10 > WSL2 > Debian12 > Docker > InvokeAI. This is my docker compose:

```yaml
invokeai-nvidia:
  build:
    context: ./InvokeAI
    dockerfile: docker/Dockerfile
  environment:
    - INVOKEAI_ROOT=/invokeai
    - INVOKEAI_LOG_LEVEL=info
    - INVOKEAI_HASHING_ALGORITHM=blake3_multi
  volumes:
    - ./invokeai:/invokeai
    - ./models:/invokeai/models
    - /mnt/g/Main/VirtualBox/WSL/models:/invokeai/models/g-mnt
  network_mode: host
  tty: true
  stdin_open: true
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
```
