### ISSUE TITLE
[bug]: (v4.2.5) txt2img failed with random noise 

### ISSUE THREAD

**Issue by leo9800** [invoke-ai/InvokeAI#6559]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

None (CPU)

### Version number

4.2.5, 4.2.5post1

### Browser

Firefox 127.0.2

### Python dependencies

```json
{
  "accelerate": "0.30.1",
  "compel": "2.0.2",
  "cuda": "12.1",
  "diffusers": "0.27.2",
  "numpy": "1.26.4",
  "opencv": "4.9.0.80",
  "onnx": "1.15.0",
  "pillow": "10.3.0",
  "python": "3.11.4",
  "torch": "2.2.2+cu121",
  "torchvision": "0.17.2+cu121",
  "transformers": "4.41.1",
  "xformers": "0.0.25.post1"
}
```

### What happened

Starts from v4.2.5, (incl. v4.2.5post1, which has a tag but not yet available from release page) InvokeAI could not generate image properly with txt2img.

The detailed behaviour is described as below:

1. After upgrade to v4.2.5(+), the first image generation would be fine.
2. from second generation, no matter it is in a same batch with the first one or not, the generation result seems to be noise. (Completely unrelated to the text prompt)
3. Then all generations would yield similar results.
4. Restart InvokeAI or change to another model would yield 1 proper image, but the second and further would have same problem. (Returns to point 1 of this issue)

Here are some samples of problematic images generated by v4.2.5:

![Screenshot from 2024-06-29 16-26-02](https://github.com/invoke-ai/InvokeAI/assets/13928879/54a85495-a200-420d-86de-49dc756d4c06)
![Screenshot from 2024-06-29 16-26-06](https://github.com/invoke-ai/InvokeAI/assets/13928879/816b7f00-b876-4038-9c20-2bb7e1ac0d52)
![Screenshot from 2024-06-29 16-26-08](https://github.com/invoke-ai/InvokeAI/assets/13928879/2e858c6d-f5ad-47b8-99c4-f18d03c0588a)

All of models are SDXL or Pony

I also find someone on InvokeAI Discord Server seems to experencing similar issues, but the author was on MPS (Apple Silicon), while I am using CPU. (no GPU on my server)

- https://discord.com/channels/1020123559063990373/1149510134058471514/1255983198081384581
- https://discord.com/channels/1020123559063990373/1149510134058471514/1255983874803237037
- https://discord.com/channels/1020123559063990373/1149510134058471514/1255998468800118824

### What you expected to happen

Image generated properly.

### Additional context

I run InvokeAI on my homelab server with Docker, and the Docker image is built from the `Dockerfile` in this repository.

The server is running Arch Linux, but given that InvokeAI is running in a Docker container, the host OS should not matter.

There is no GPU on this server so InvokeAI do the computings on CPU.

Besides, Apache HTTP Server (`httpd`) is running in front of InvokeAI to provide a SSL-termination reverse proxy.

Below is my process building docker image, take v4.2.5 as example:
```bash
$ git clone https://github.com/invoke-ai/InvokeAI.git
$ cd InvokeAI/
$ git checkout v4.2.5
$ cd docker/
$ docker build -t registry_domain_omitted/docker/invokeai:4.2.5 -t registry_domain_omitted/docker/invokeai:latest -f ./Dockerfile ..
```

And docker compose file:

```yaml
services:
  invokeai:
    image: registry_domain_omitted/docker/invokeai:4.2.5
    container_name: invokeai
    environment:
      - INVOKEAI_ROOT=/invokeai
      - HF_HOME=/huggingface
      - CONTAINER_UID=60
      - CONTAINER_GID=60
    ports:
      - 127.0.0.1:50102:9090
    volumes:
      - ./invokeai-data:/invokeai
      - ./invokeai-huggingface:/huggingface
      - ./invokeai-imports:/imports
    tty: true
    stdin_open: true
    restart: unless-stopped
```

And `httpd` configuration:

```
<VirtualHost *:443>
	ServerName invokeai.domain.tld
	SSLEngine On
	SSLCertificateFile /etc/letsencrypt/live/domain.tld/fullchain.pem
	SSLCertificateKeyFile /etc/letsencrypt/live/domain.tld/privkey.pem

	AllowEncodedSlashes NoDecode

	ProxyPass / http://127.0.0.1:50102/ nocanon upgrade=websocket
	ProxyPreserveHost On

	RequestHeader set "X-Real-IP" expr=%{REMOTE_ADDR}
	RequestHeader set "X-Forwarded-For" expr=%{REMOTE_ADDR}
	RequestHeader set "X-Forwarded-Port" expr=%{SERVER_PORT}
	RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
	RequestHeader set "X-Forwarded-Ssl" expr=%{HTTPS}
</VirtualHost>
```

I had not change any of above during upgrading from v4.2.4 to v4.2.5, besides, by downgrading back to v4.2.4, the issue no longer exists. So I believe these configurations are fine.
