### ISSUE TITLE
[bug]: Clearing queues in mid generation does not free VRAM, even when configured to do so

### ISSUE THREAD

**Issue by systemofapwne** [invoke-ai/InvokeAI#6759]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 4000 ADA SFF

### GPU VRAM

20GB

### Version number

4.2.8rc2

### Browser

Brave v1.68.141

### What happened

Might be related to https://github.com/invoke-ai/InvokeAI/issues/6613

**Here, Invoke is configured with "vram: 0.1" in invokeai.yaml in order to always free up VRAM after generation.**

Clicking "Cancel and Clear All Items" during image generation does however not free VRAM: It just sticks at what it used to need during image generation (e.g. 7 GB)

However, waiting until the queue finished clears VRAM as expected: Not entirely though - might be a different bug - but at least down to 1.8 GB on my system

### What you expected to happen

No matter if a queue finished or has been aborted via the "Cancel and Clear All Items" button, VRAM should be freed.

### How to reproduce the problem

Normal working operation (yet a bit too much VRAM usage)
1. Configure InvokeAI with 'vram: 0.1' which is supposed to free VRAM > 100 MB after any generation
2. Generate any image and observe VRAM via `nvidia-smi --loop-ms=1000`. It will rise 7 GB on my system (SDXL)
3.Once everything in the queue has been generated, VRAM drops down significantly. On my system down to 1.8 GB. Still way more than expected but "quiet low" though

Trigger the bug (excessive VRAM usage)
1. Configure InvokeAI with 'vram: 0.1' which is supposed to free VRAM > 100 MB after any generation
2. Generate any image and observe VRAM via `nvidia-smi --loop-ms=1000`. It will rise 7 GB on my system (SDXL)
3.Abort the generation by clicking on the 'Cancel and Clear All Items'. VRAM usage stays at 7 GB

### Discord username

systemofapwne

**Comment by systemofapwne** [comment]
Bug is still present in latest 5.0.

**Comment by systemofapwne** [comment]
> I think the behaviour is as expected. Can you please try `lazy_offload: false` in `invokeai.yaml`?
> 
> With `lazy_offload: true` (the default), we expect VRAM to _not_ be cleared after generation. So if I understand how the model loading works, it's actually unexpected that VRAM is emptied after generation.

Rather sounds like a bug to me, that "letting the queue finish" will clear VRAM as expected (with `vram: 0.1` set) while manually killing the queue does not.
However, setting `lazy_offload: false` as you suggested finally clears VRAM, no matter if the queue finishs or gets aborted.
Thank you

**Comment by psychedelicious** [comment]
Yes, that's unexpected behavior. Would you please created a separate issue for this? Doesn't need to be super detailed, can link to this issue for context. Just don't want this to get lost.

**Comment by systemofapwne** [comment]
The problem now is back after the switch to the new caching and memory logic.
My config is set like this:

```yaml
# Put user settings here - see https://invoke-ai.github.io/InvokeAI/features/CONFIGURATION/:
# Store models in system RAM until usage up to this amount of RAM (used to be DEPRECATED ram)
max_cache_ram_gb: 20.0
# Make this intentionally very small, to clear up vram ASAP after generation (used to be DEPRECATED vram)
max_cache_vram_gb: 0.1
# DEPRECATED: Disable lazy_offload, so it will always unload models when generation has finished
lazy_offload: false
# Disable partial loading (speeds things up but will fail on giant models)
enable_partial_loading: false
```

Before, unloading vram when a queue was aborted worked with `vram` set to something small and `lazy_offload: false`. Now, since both settings are deprecated, I cannot replicate the same behaviour with `enable_partial_loading: false` and `max_cache_vram_gb: 0.1`.
