### ISSUE TITLE
[bug]: Segmentation fault when launching invokeai-web

### ISSUE THREAD

**Issue by max-maag** [invoke-ai/InvokeAI#7091]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

AMD (ROCm)

### GPU model

RX 6650 XT

### GPU VRAM

8GB

### Version number

5.1.1

### Browser

n/a

### What happened

After a fresh install of v5.1.1 I ran `invoke.sh` and selected the option for generating images with the browser. This resulted in a segmentation fault.

Console output:

```
Generate images with a browser-based interface
The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
./invoke.sh: line 37: 11505 Segmentation fault      (core dumped) invokeai-web $PARAMS
```

### What you expected to happen

The invoke server starts without error.

### How to reproduce the problem

- Execute `invoke.sh`.
- Select option 1.

### Additional context

I tried starting the server with the default `invokeai.yaml`. I also tried starting it with the following config:

```YAML
# Internal metadata - do not edit:
schema_version: 4.0.2

# Put user settings here - see https://invoke-ai.github.io/InvokeAI/features/CONFIGURATION/:
host: 127.0.0.1
port: 9090
allow_origins: [localhost]
allow_credentials: true
allow_methods:
- '*'
allow_headers:
- '*'
log_tokenization: false
patchmatch: true
models_dir: /usr/share/ai-models
convert_cache_dir: models/.convert_cache
download_cache_dir: models/.download_cache
legacy_conf_dir: configs
db_dir: databases
outputs_dir: outputs
custom_nodes_dir: nodes
log_handlers:
- console
- file=/opt/InvokeAI/log.txt
log_format: color
log_level: debug
log_sql: false
use_memory_db: false
dev_reload: false
profile_graphs: false
profiles_dir: profiles
ram: 24.0
vram: 6.0
lazy_offload: true
log_memory_usage: false
device: auto
precision: float16
sequential_guidance: false
attention_type: auto
attention_slice_size: auto
force_tiled_decode: false
pil_compress_level: 1
max_queue_size: 10000
clear_queue_on_startup: false
node_cache_size: 512
hashing_algorithm: blake3_multi
#remote_api_tokens:
#- url_regex: cool-models.com
#  token: my_secret_token
#- url_regex: nifty-models.com
#  token: some_other_token
scan_models_on_startup: false
```

I also tried running the script with the environment variables `CUDA_VERSION=gfx1030 HSA_OVERRIDE_GFX_VERSION=10.3.0`. This was necessary in older versions to not segfault but didn't help here.

The last version I tested was 4.2.7post1 which ran without issues. At least with the environment variables mentioned above.

I noticed that the installer downloaded many CUDA dependencies even though I selected ROCm. I don't know if this is related.
