### ISSUE TITLE
MacOs - CONDA reports conflits on 2.0-rc 

### ISSUE THREAD

**Issue by i3oc9i** [invoke-ai/InvokeAI#932]
**ENV**: MacOs
**commit**: 44e3995425bcc850afafd52b8abfc0558769a0a4

Before to start a new test campain I use to do a complete fresh install.
But conda fails on creating a new environment because of conflicts:

```
conda clean --yes --all

PIP_EXISTS_ACTION=w CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac.yml 

```
Also reported by the guthub action https://github.com/invoke-ai/InvokeAI/actions/runs/3178292811/jobs/5179635594

FYI 
the commit **Merge branch 'Any-Winter-4079-Textual_Inversion' of github.com:Any-Wi…** 0a217b5f15410c588309df6cc2b67f87e40d3a39 introduce dependecies conflicts

The following fix the issue
```
diff --git a/environment-mac.yml b/environment-mac.yml
index 70df3b8..5cb96ce 100644
--- a/environment-mac.yml
+++ b/environment-mac.yml
@@ -33,7 +33,7 @@ dependencies:
   - openh264==2.3.0
   - onnx==1.12.0
   - onnxruntime==1.12.1
-  - protobuf==3.19.4
+  - protobuf==3.20.1
   - pudb==2022.1
   - pytorch-lightning==1.7.5
   - scipy==1.9.1
@@ -48,7 +48,6 @@ dependencies:
     - dependency_injector==4.40.0
     - eventlet
     - opencv-python==4.6.0
-    - protobuf==3.20.1
     - realesrgan==0.2.5.0
     - send2trash==1.8.0
     - test-tube==0.7.5
  ```

**Comment by lstein** [comment]
@Any-Winter-4079 will this patch break your work on textual Inversion? Obviously it is a higher priority to make installs work.

**Comment by Any-Winter-4079** [comment]
`protobuf==3.20.1` breaks Textual Inversion if I remember correctly, but I have it set up with
`protobuf                  3.19.4                   pypi_0    pypi` so I think the solution is not to change protobuf, but update the version of other packages.

**Comment by i3oc9i** [comment]
@Any-Winter-4079 

here is a log with the reported conflits 

[Log at 2022-10-05 3-41-40 PM.txt](https://github.com/invoke-ai/InvokeAI/files/9716079/Log.at.2022-10-05.3-41-40.PM.txt)

also note that there are two **protobuf** dependencies in the original _environment-mac.yml_ file, and they are not alligned.

**Comment by lstein** [comment]
As soon as you find a solution that works let me know. I'm going through the various bugs reported in the last six hours and hope to release another RC later today.

**Comment by Any-Winter-4079** [comment]
That's a lot of conflicts. Maybe @tmm1 can help you since I'm in class now. I think he managed to get it to work as well.

Honestly, I have my own environment and whenever a new dependency is added, I just `pip install` it. I have my own versions that work (e.g. Python 3.9.13, Pytorch 1.12.1 etc.) and I don't update those so easily, regardless of what `environment-mac.yaml` says.

I'll try to take a look after class.

**Comment by i3oc9i** [comment]
> Honestly, I have my own environment and whenever a new dependency is added, I just `pip install` it. I have my own versions that work (e.g. Python 3.9.13, Pytorch 1.12.1 etc.) and I don't update those so easily, regardless of what `environment-mac.yaml` says.

I have my environment, too. Here we are going to do a new release, so IMHO test campain have to begin with a frech install.

**Comment by lstein** [comment]
Point is well taken. I'm updating the pre-flight testing document to ask people to test fresh installs.

**Comment by Any-Winter-4079** [comment]
@lstein @i3oc9i In between classes, but here are my versions
`python                    3.9.13`
conda
```
pytorch                   1.12.1                
albumentations            1.2.1         
coloredlogs               15.0.1           
einops                    0.4.1    
grpcio                    1.46.4        
humanfriendly             10.0
imageio                   2.21.2
imageio-ffmpeg            0.4.7
imgaug                    0.4.0
kornia                    0.6.7
mpmath                    1.2.1
nomkl                     1.0
numpy                     1.23.2
omegaconf                 2.1.1
openh264                  2.3.0
onnx                      1.12.0
onnxruntime               1.12.1
protobuf                  3.19.5
pudb                      2022.1
pytorch-lightning         1.7.5
scipy                     1.9.1
streamlit                 1.12.2
sympy                     1.10.1
tensorboard               2.10.0
torchmetrics              0.9.3
```
pip
```
flask 2.1.3
flask_socketio 5.3.0
flask_cors 3.0.10
dependency_injector 4.40.0
eventlet 0.33.1
opencv-python 4.6.0
realesrgan 0.2.5.0
send2trash 1.8.0
test-tube 0.7.5
transformers 4.21.2
torch-fidelity 0.3.0
```

**Comment by lstein** [comment]
Thanks for doing this! Ironically, I'm working on the release between meetings with students.

**Comment by Any-Winter-4079** [comment]
@lstein @i3oc9i 
I updated environment-mac.yml to the following:
```
name: ldm
channels:
  - pytorch
  - conda-forge
dependencies:
  - python==3.9.13
  - pip==22.2.2

  # pytorch left unpinned
  - pytorch==1.12.1
  - torchvision==0.13.1

  # I suggest to keep the other deps sorted for convenience.
  # To determine what the latest versions should be, run:
  #
  # ```shell
  # sed -E 's/ldm/ldm-updated/;20,99s/- ([^=]+)==.+/- \1/' environment-mac.yml > environment-mac-updated.yml
  # CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac-updated.yml && conda list -n ldm-updated | awk ' {print "  - " $1 "==" $2;} '
  # ```
  - albumentations==1.2.1
  - coloredlogs==15.0.1
  - einops==0.4.1
  - grpcio==1.46.4
  - humanfriendly==10.0
  - imageio==2.21.2
  - imageio-ffmpeg==0.4.7
  - imgaug==0.4.0
  - kornia==0.6.7
  - mpmath==1.2.1
  - nomkl=1.0
  - numpy==1.23.2
  - omegaconf==2.1.1
  - openh264==2.3.0
  - onnx==1.12.0
  - onnxruntime==1.12.1
  - pudb==2022.1
  - pytorch-lightning==1.7.5
  - scipy==1.9.1
  - streamlit==1.12.2
  - sympy==1.10.1
  - tensorboard==2.10.0
  - torchmetrics==0.9.3
  - pip:
      - flask==2.1.3
      - flask_socketio==5.3.0
      - flask_cors==3.0.10
      - dependency_injector==4.40.0
      - eventlet==0.33.1
      - opencv-python==4.6.0
      - protobuf==3.19.5
      - realesrgan==0.2.5.0
      - send2trash==1.8.0
      - test-tube==0.7.5
      - transformers==4.21.2
      - torch-fidelity==0.3.0
      - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
      - -e git+https://github.com/openai/CLIP.git@main#egg=clip
      - -e git+https://github.com/Birch-san/k-diffusion.git@mps#egg=k_diffusion
      - -e git+https://github.com/lstein/GFPGAN@fix-dark-cast-images#egg=gfpgan
      - -e .
variables:
  PYTORCH_ENABLE_MPS_FALLBACK: 1

```
The only change, other than adding versions for `python`, `pytorch`, `torchvision`, etc., is removing `protobuf` from `dependencies:` and updating it on `pip:` with version 3.19.5

It seems to work better. Runs successfully up to:
`- -e git+https://github.com/Birch-san/k-diffusion.git@mps#egg=k_diffusion`
Seems to fail for GFPGAN
`error: can't find Rust compiler`
Test with `PIP_EXISTS_ACTION=w CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac.yml`

**Comment by Any-Winter-4079** [comment]
Okay, so leaving my stable diffusion environment with `conda activate`, I get rid of the rust error.
Instead for GFPGAN:
```
Pip subprocess error:
  Running command git fetch -q --tags
  Running command git reset --hard -q 24268930bf1dce879235a7fddd0b2355b84d7ea6
  Running command git fetch -q --tags
  Running command git reset --hard -q d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
  Running command git fetch -q --tags
  Running command git reset --hard -q 7f16b2c33411f26b3eae78d10648d625cb0c1095
  Running command git fetch -q --tags
  fatal: unable to access 'https://github.com/lstein/GFPGAN/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443
  error: subprocess-exited-with-error

```

**Comment by lstein** [comment]
> Fails later with `error: can't find Rust compiler` Test with `PIP_EXISTS_ACTION=w CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac.yml`

(muffled scream)

Which step is requiring the Rust compiler?

**Comment by i3oc9i** [comment]
I have successfully create a fresh CONDA environment with your file @Any-Winter-4079 

[environment-mac.yml.zip](https://github.com/invoke-ai/InvokeAI/files/9717237/environment-mac.yml.zip)

**Rust is installed on my macos.**

I did some rapid test with the web interface: generation, upscaling, and restore face work as expected

**Comment by Any-Winter-4079** [comment]
@lstein 
This is where the rust error originated
```
Building wheel for tokenizers (pyproject.toml) did not run successfully.
  │ exit code: 1
```
I was in my current stable diffusion environment, trying to create a new one.

After leaving that environment with `conda activate` the error is
```
fatal: unable to access 'https://github.com/lstein/GFPGAN/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443
  error: subprocess-exited-with-error
```

**Comment by Any-Winter-4079** [comment]
@i3oc9i Awesome!

**Comment by lstein** [comment]
> Okay, so leaving my stable diffusion environment with `conda activate` before `PIP_EXISTS_ACTION=w CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac.yml`, I get rid of the rust error (?). Instead, I get this error for GFPGAN:
> 
> ```
> Pip subprocess error:
>   Running command git fetch -q --tags
>   Running command git reset --hard -q 24268930bf1dce879235a7fddd0b2355b84d7ea6
>   Running command git fetch -q --tags
>   Running command git reset --hard -q d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
>   Running command git fetch -q --tags
>   Running command git reset --hard -q 7f16b2c33411f26b3eae78d10648d625cb0c1095
>   Running command git fetch -q --tags
>   fatal: unable to access 'https://github.com/lstein/GFPGAN/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443
>   error: subprocess-exited-with-error
> ```

Why would all the other git+https lines work and this one fail? I'm going to check whether my fork of GFPGAN is still necessary.

**Comment by i3oc9i** [comment]
@lstein 
I use this sequence to create a fresh install (rust is installed via `brew install cmake rust`)
```
conda env remove -n ldm
conda clean --yes --all
PIP_EXISTS_ACTION=w CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac.yml
```

**Comment by Any-Winter-4079** [comment]
@lstein Yes, using @i3oc9i command to install rust gets rid of all errors. Not sure what the `github.com:443` error was all about.

So in summary,
`brew install cmake rust` if rust does not exist
`PIP_EXISTS_ACTION=w CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac.yml`

**Comment by Any-Winter-4079** [comment]
I do get` ## NOT FOUND: GFPGAN model not found at ./src/gfpgan/experiments/pretrained_models/GFPGANv1.4.pth` but I guess it's meant to be added manually.

**Comment by i3oc9i** [comment]
> I do get` ## NOT FOUND: GFPGAN model not found at ./src/gfpgan/experiments/pretrained_models/GFPGANv1.4.pth` but I guess it's meant to be added manually.

`python scripts/preload_models.py` does the job I guess, but I have already downloaded that, so I link to the model file

```
mkdir -p ./models/ldm/stable-diffusion-v1
pushd ./models/ldm/stable-diffusion-v1
ln -s ~/Code/Ai/@Stuffs/models/sd-v1-4.ckpt model.ckpt
popd

mkdir -p ./src/gfpgan/experiments/pretrained_models
pushd ./src/gfpgan/experiments/pretrained_models
ln -s ~/Code/Ai/@Stuffs/models/GFPGANv1.4.pth GFPGANv1.4.pth
popd

mkdir -p ./ldm/dream/restoration/codeformer/weights
pushd ./ldm/dream/restoration/codeformer/weights
ln -s ~/Code/Ai/@Stuffs/models/codeformer.pth codeformer.pth
popd
```

**Comment by Any-Winter-4079** [comment]
Oh, yeah, I forgot about that. I've been having the `pretrained_models` for quite some time, so I completely forgot about that command.
I see a new install gets rid of it though, even if it exists.

**Comment by Any-Winter-4079** [comment]
So, summing up for @lstein 
`brew install cmake rust` if rust does not exist
`PIP_EXISTS_ACTION=w CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac.yml`
`python scripts/preload_models.py`

environment-mac.yaml
```
name: ldm
channels:
  - pytorch
  - conda-forge
dependencies:
  - python==3.9.13
  - pip==22.2.2

  # pytorch left unpinned
  - pytorch==1.12.1
  - torchvision==0.13.1

  # I suggest to keep the other deps sorted for convenience.
  # To determine what the latest versions should be, run:
  #
  # ```shell
  # sed -E 's/ldm/ldm-updated/;20,99s/- ([^=]+)==.+/- \1/' environment-mac.yml > environment-mac-updated.yml
  # CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac-updated.yml && conda list -n ldm-updated | awk ' {print "  - " $1 "==" $2;} '
  # ```
  - albumentations==1.2.1
  - coloredlogs==15.0.1
  - einops==0.4.1
  - grpcio==1.46.4
  - humanfriendly==10.0
  - imageio==2.21.2
  - imageio-ffmpeg==0.4.7
  - imgaug==0.4.0
  - kornia==0.6.7
  - mpmath==1.2.1
  - nomkl=1.0
  - numpy==1.23.2
  - omegaconf==2.1.1
  - openh264==2.3.0
  - onnx==1.12.0
  - onnxruntime==1.12.1
  - pudb==2022.1
  - pytorch-lightning==1.7.5
  - scipy==1.9.1
  - streamlit==1.12.2
  - sympy==1.10.1
  - tensorboard==2.10.0
  - torchmetrics==0.9.3
  - pip:
      - flask==2.1.3
      - flask_socketio==5.3.0
      - flask_cors==3.0.10
      - dependency_injector==4.40.0
      - eventlet==0.33.1
      - opencv-python==4.6.0
      - protobuf==3.19.5
      - realesrgan==0.2.5.0
      - send2trash==1.8.0
      - test-tube==0.7.5
      - transformers==4.21.2
      - torch-fidelity==0.3.0
      - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
      - -e git+https://github.com/openai/CLIP.git@main#egg=clip
      - -e git+https://github.com/Birch-san/k-diffusion.git@mps#egg=k_diffusion
      - -e git+https://github.com/lstein/GFPGAN@fix-dark-cast-images#egg=gfpgan
      - -e .
variables:
  PYTORCH_ENABLE_MPS_FALLBACK: 1

```
